apiVersion: apps/v1
kind: Deployment
metadata:
  name: airfleet-backend-deployment
  namespace: airfleet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: airfleet-backend
  template:
    metadata:
      labels:
        app: airfleet-backend
    spec:
      containers:
      - name: airfleet-backend
        image: momin21/airfleet-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://airfleet-mongodb-service:27017/airfleet"