apiVersion: apps/v1
kind: Deployment
metadata:
  name: airfleet-frontend-deployment
  namespace: airfleet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: airfleet-frontend
  template:
    metadata:
      labels:
        app: airfleet-frontend
    spec:
      containers:
      - name: airfleet-frontend
        image: momin21/airfleet-frontend:latest
        ports:
        - containerPort: 80