apiVersion: v1
kind: Service
metadata:
  name: airfleet-backend-service
  namespace: airfleet
spec:
  type: NodePort
  selector:
    app: airfleet-backend
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30008