apiVersion: v1
kind: Service
metadata:
  name: airfleet-frontend-service
  namespace: airfleet
spec:
  type: NodePort
  selector:
    app: airfleet-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007