apiVersion: v1
kind: Service
metadata:
  name: airfleet-mongodb-service
  namespace: airfleet
spec:
  type: ClusterIP
  selector:
    app: airfleet-mongodb
  ports:
    - port: 27017
      targetPort: 27017