apiVersion: apps/v1
kind: Deployment
metadata:
  name: airfleet-mongodb-deployment
  namespace: airfleet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airfleet-mongodb
  template:
    metadata:
      labels:
        app: airfleet-mongodb
    spec:
      containers:
      - name: airfleet-mongodb
        image: mongo:6
        ports:
        - containerPort: 27017