name: Deploy to Minikube

on: [push]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Frontend Image
        run: |
          docker build -f app/airfleet-management/Dockerfile -t momin322/airfleet-frontend:latest .
          docker push momin322/airfleet-frontend:latest

      - name: Build and Push Backend Image
        run: |
          docker build -f app/airfleet-management-backend/Dockerfile -t momin322/airfleet-backend:latest .
          docker push momin322/airfleet-backend:latest

      - name: Start Minikube
        run: |
          minikube start --driver=docker || true

      - name: Ensure Namespace Exists
        run: |
          kubectl create namespace airfleet || true

      - name: Deploy to Minikube
        run: |
          kubectl apply -f app/k8s/mongodb-deployment.yaml -n airfleet
          kubectl apply -f app/k8s/mongodb-service.yaml -n airfleet
          kubectl apply -f app/k8s/backend-deployment.yaml -n airfleet
          kubectl apply -f app/k8s/backend-service.yaml -n airfleet
          kubectl apply -f app/k8s/frontend-deployment.yaml -n airfleet
          kubectl apply -f app/k8s/frontend-service.yaml -n airfleet